#!/bin/bash
echo "🚀 Fast-CRM Frontend Demo - Now with RAG!"
echo "=========================================="
echo ""
echo "📊 Dashboard URL: http://localhost:3000"
echo ""
echo "✨ NEW: Dual-Tab Interface:"
echo "  📊 Leads Database - CRM lead management and status tracking"
echo "  💬 RAG Email History - Context-aware conversation flow"
echo ""
echo "✅ Frontend Features:"
echo "  • Real-time lead visualization with status badges"
echo "  • RAG conversation history with incoming/outgoing emails"
echo "  • Context-aware AI responses shown side-by-side"
echo "  • Auto-refresh every 30 seconds"
echo "  • Professional Tailwind CSS styling"
echo "  • Responsive design for mobile/desktop"
echo ""
echo "🎭 RAG Demo Data Shows:"
echo "  📧 Jenny's 3-email progression: Initial → Pricing → Onboarding"
echo "  🔄 Context building from ADD_LEAD to QUALIFY_LEAD"
echo "  🤖 AI responses that reference previous conversations"
echo "  🎯 Technical progression: Platform info → Trial signup → Best practices"
echo ""
echo "💡 Hackathon Demo Flow:"
echo "  1. Start on 📊 Leads Database tab - show lead counts and status"
echo "  2. Switch to 💬 RAG Email History tab - show conversation flow"
echo "  3. Highlight how AI responses build on previous context"
echo "  4. Send new test email to show real-time updates"
echo ""
echo "🔗 API Endpoints:"
echo "  POST /api/v1/process_email - Process new emails with RAG context"
echo "  GET  /api/v1/leads - Fetch leads for CRM dashboard"
echo ""
echo "Press Ctrl+C to stop the demo server"